openapi: 3.0.0
info:
  title: main.v1.json
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /jobs/search:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-jobs-search
  '/job/getdetails/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-job-getdetails-code
components:
  schemas: {}
